### ISSUE TITLE
Doesn't work or outdated.

### ISSUE THREAD

**Issue by CryptoRescue** [nasa8x/genesis-block#1]
Doesn't work or outdated.

python gen.py -a lyra2re
04ffff001d0104435468652054696d65732031382f4a616e2f323031382e20446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c732e
Traceback (most recent call last):
  File "gen.py", line 260, in <module>
    main()
  File "gen.py", line 17, in main
    tx = create_transaction(input_script, output_script,options)
  File "gen.py", line 74, in create_transaction
    transaction = Struct("transaction",
NameError: global name 'Struct' is not defined

That's when trying to generate the Lyra2re algo genesis block as a test.

**Comment by nasa8x** [comment]
I do not know what's error. Because I tried and did not generate any errors.

> 04ffff001d0104435468652054696d65732031382f4a616e2f323031382e20446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c732e
> algorithm: lyra2re
> merkle hash: 26f31a72cb4a7b97caeeb49a9177e40d71f09de7a04f0380f7889a8c2494973a
> pszTimestamp: The Times 18/Jan/2018. Don't work for weekends, work for our goals.
> pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
> time: 1519486222
> bits: 0x1e0ffff0
> Searching for genesis hash...
> genesis hash found!
> nonce: 267811
> genesis hash: 00000712f28a14716df6e00e5f14f33ef0945cf771cd25f63faefc606b577fa6
> Nasas-MacBook-Pro:genesis-block nasa8x$ 04ffff001d0104435468652054696d65732031382f4a616e2f323031382e20446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c732e

**Comment by rushiraj111** [comment]
I am getting same error:

python gen.py -a quark -t 1517542208 -z "Don't work for weekends, work for our goals - 18/Jan/2018." -p "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f" 04ffff001d01043a446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c73202d2031382f4a616e2f323031382e Traceback (most recent call last): File "gen.py", line 261, in <module> main() File "gen.py", line 18, in main tx = create_transaction(input_script, output_script,options) File "gen.py", line 76, in create_transaction Bytes("version", 4), TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by Oxygencoin** [comment]
I have the same error:

Traceback (most recent call last): File "gen.py", line 261, in main() File "gen.py", line 18, in main tx = create_transaction(input_script, output_script,options) File "gen.py", line 76, in create_transaction Bytes("version", 4), TypeError: init() takes exactly 2 arguments (3 given)

**Comment by Oxygencoin** [comment]
debian@debian:~/genesis-block$ python gen.py -a quark -t 1509408000 -z "start 10/31/2017 12:00am (UTC)" -p "04aee5271cc17e6477ed9ff5a6ac1a4fdd5ca3457b28f19c738ebc69a7d5c1de9fac19c226c76a9ea912228b9c0bfd127d28bd36ca7c3d20befe42185e09318d52"
04ffff001d0104257374617274206f787967656e2031302f33312f323031372031323a3030616d202855544329
algorithm: quark
merkle hash: 1a7c02fcc66b4891d8e0b2b84d2e7d186d6c5347f08e78dcd85faa241f0211a2
pszTimestamp: start oxygen 10/31/2017 12:00am (UTC)
pubkey: 04aee5271cc17e6477ed9ff5a6ac1a4fdd5ca3457b28f19c738ebc69a7d5c1de9fac19c226c76a9ea912228b9c0bfd127d28bd36ca7c3d20befe42185e09318d52
time: 1509408000
bits: 0x1e0ffff0
Searching for genesis hash...
Cannot run quark algorithm: module quark_hash not found

SOS!!!

**Comment by tofutim** [comment]
sudo pip install quark-hash

**Comment by phantanthanh1996** [comment]
Hello, i have get same error 
~/genesis-block# python gen.py -a quark -t 1520906820 -z "Test with new coin" -p "04c10e83b2703ccf322f7dbd62dd5855ac7c10bd055814ce121ba32607d573b8810c02c0582aed05b4deb9c4b77b26d92428c61256cd42774babea0a073b2ed0c9"
Traceback (most recent call last):
  File "gen.py", line 6, in <module>
    from construct import *
ImportError: No module named construct
 
Pls help me!

**Comment by rushiraj111** [comment]
@phantanthanh1996 install following deps:

sudo pip install construct
sudo pip install quark-hash

**Comment by rushiraj111** [comment]
@tofutim Working now 👍

**Comment by phantanthanh1996** [comment]
python gen.py -a quark -t 1520906820 -z "Test with new coin" -p "04c10e83b2703ccf322f7dbd62dd5855ac7c10bd055814ce121ba32607d573b8810c02c0582aed05b4deb9c4b77b26d92428c61256cd42774babea0a073b2ed0c9"
04ffff001d010412546573742077697468206e657720636f696e
Traceback (most recent call last):
  File "gen.py", line 261, in <module>
    main()
  File "gen.py", line 18, in main
    tx = create_transaction(input_script, output_script,options)
  File "gen.py", line 76, in create_transaction
    Bytes("version", 4),
TypeError: __init__() takes exactly 2 arguments (3 given)
Hi, i am get new error.

**Comment by phantanthanh1996** [comment]
Hi rushiraj111, with version python do you use to generate?

**Comment by rushiraj111** [comment]
@phantanthanh1996 try this:

pip install construct==2.5.2

**Comment by marvic41** [comment]
only x11 is not working. Is code commented ?

**Comment by nasa8x** [comment]
Try node.js version more algorithms: https://github.com/nasa8x/node-genesis-block

**Comment by FndNur1Labs** [comment]
how about genesis for algo cryptonight?

**Comment by wkibbler** [comment]
im getting this error. have managed to successfully hash one before this

Traceback (most recent call last):
  File "gen.py", line 261, in <module>
    main()
  File "gen.py", line 18, in main
    tx = create_transaction(input_script, output_script,options)
  File "gen.py", line 103, in create_transaction
    return transaction.build(tx)
  File "/home/william/.local/lib/python2.7/site-packages/construct/core.py", line 212, in build
    self.build_stream(obj, stream)
  File "/home/william/.local/lib/python2.7/site-packages/construct/core.py", line 219, in build_stream
    self._build(obj, stream, Container())
  File "/home/william/.local/lib/python2.7/site-packages/construct/core.py", line 691, in _build
    sc._build(subobj, stream, context)
  File "/home/william/.local/lib/python2.7/site-packages/construct/core.py", line 330, in _build
    _write_stream(stream, self.length, bchr(obj) if isinstance(obj, int) else obj)
  File "/home/william/.local/lib/python2.7/site-packages/construct/core.py", line 312, in _write_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
construct.core.FieldError: expected 67, found 65

**Comment by FndNur1Labs** [comment]
bug updates

**Comment by metic222** [comment]
my Quark genesis block doesn't work for my coin, It just fails and I get assertion core dumped error.
used this script

===================================================================
                                                            **DEBIAN COMMAND LINE**
===================================================================
```
root@debian:~/genesis-block# python gen.py -a quark -z "30th April - Worx Birthday YAY!" –p "0460f3c0dc9030b06deecde1dcdf38a0c964fca7b91f3af4891bf6d4afd19e0ca8c49c4be32514cf9cfe7d7815ea881784165b8cc04e56cadce0dd457d75215c08" -t 1527929962
04ffff001d01041f3330746820417072696c202d20576f72782042697274686461792059415921
algorithm: quark
merkle hash: 78c4cba5e2fdae012174f57f89628040e661d0bede071374e2f7cf10aaecc6b6
pszTimestamp: 30th April - Worx Birthday YAY!
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
time: 1527929962
bits: 0x1e0ffff0
Searching for genesis hash...
genesis hash found!imate: 12.2 h
nonce: 1203045
genesis hash: 000003d2d9c72c327df1b3b2b94cfc07c9e788082ff23e14f06c53ac78d7c757
```


===================================================================
                                             **WHEN STARTING WALLET DAEMON I GET THIS ERROR...**
===================================================================
```
chainparams.cpp:139: CMainParams::CMainParams(): Assertion
`hashGenesisBlock ==
uint256("0x000003d2d9c72c327df1b3b2b94cfc07c9e788082ff23e14f06c53ac78d7c757")'
failed.
Aborted (core dumped)
```

-------------------------------------------------------------------------------------------------------------------
Rejected my hash?  I have changed all these details in the chainparams.cpp and am getting these issues, why would this be happening? is there another file that has the genesis hash?

**Comment by nasa8x** [comment]
Are you sure add right:
time: 1527929962
nonce: 1203045

**Comment by metic222** [comment]
thanks for the reply, yes I have checked over the chainparams.cpp and have used the same variables used in genesis block creation, this is purely for research purposes might I add =) .

```
/**
 * Main network
 */

//! Convert the pnSeeds6 array into usable address objects.
static void convertSeed6(std::vector<CAddress>& vSeedsOut, const
SeedSpec6* data, unsigned int count)
{
    // It'll only connect to one or two seed nodes because once it connects,
    // it'll get a pile of addresses with newer timestamps.
    // Seed nodes are given a random 'last seen time' of between one and two
    // weeks ago.
    const int64_t nOneWeek = 7 * 24 * 60 * 60;
    for (unsigned int i = 0; i < count; i++) {
        struct in6_addr ip;
        memcpy(&ip, data[i].addr, sizeof(ip));
        CAddress addr(CService(ip, data[i].port));
        addr.nTime = GetTime() - GetRand(nOneWeek) - nOneWeek;
        vSeedsOut.push_back(addr);
    }
}

//   What makes a good checkpoint block?
// + Is surrounded by blocks with reasonable timestamps
//   (no blocks before with a timestamp after, none after with
//    timestamp before)
// + Contains no strange transactions

static Checkpoints::MapCheckpoints mapCheckpoints =
    boost::assign::map_list_of
    (0, uint256("0x000003d2d9c72c327df1b3b2b94cfc07c9e788082ff23e14f06c53ac78d7c757"));

static const Checkpoints::CCheckpointData data = {
    &mapCheckpoints,
    1527929962, // * UNIX timestamp of last checkpoint block
    0,    // * total number of transactions between genesis and last checkpoint
                //   (the tx=... number in the SetBestChain debug.log lines)
    2000        // * estimated number of transactions per day after checkpoint
};

static Checkpoints::MapCheckpoints mapCheckpointsTestnet =
    boost::assign::map_list_of(0, uint256("0x"));
static const Checkpoints::CCheckpointData dataTestnet = {
    &mapCheckpointsTestnet,
    0,
    0,
    0};

static Checkpoints::MapCheckpoints mapCheckpointsRegtest =
    boost::assign::map_list_of(0, uint256("0x"));
static const Checkpoints::CCheckpointData dataRegtest = {
    &mapCheckpointsRegtest,
    0,
    0,
    0};

class CMainParams : public CChainParams
{
public:
    CMainParams()
    {
        networkID = CBaseChainParams::MAIN;
        strNetworkID = "main";
        /**
         * The message start string is designed to be unlikely to
occur in normal data.
         * The characters are rarely used upper ASCII, not valid as
UTF-8, and produce
         * a large 4-byte int at any alignment.
         */
        pchMessageStart[0] = 0xf4;
        pchMessageStart[1] = 0x49;
        pchMessageStart[2] = 0xba;
        pchMessageStart[3] = 0x56;
        vAlertPubKey =
ParseHex("04ba7623e063dbd8499f0a119b42280aa5e9a6c991436e5c3bb456de2b16cd3df8556ff3c3d48d4c1a9e1a8ae72896ce43b363212a0b917754e63a611ab729caaf");
        nDefaultPort = 3300;
        bnProofOfWorkLimit = ~uint256(0) >> 20;
        nSubsidyHalvingInterval = 210000;
        nMaxReorganizationDepth = 100;
        nEnforceBlockUpgradeMajority = 750;
        nRejectBlockOutdatedMajority = 950;
        nToCheckBlockUpgradeMajority = 1000;
        nMinerThreads = 0;
        nTargetTimespan = 1 * 60;
        nTargetSpacing = 1 * 60;
        nLastPOWBlock = 1430;
        nMaturity = 100;
        nMasternodeCountDrift = 20;
    nMasternodeColleteralLimxDev = 1000;
//Params().MasternodeColleteralLimxDev()
        nModifierUpdateBlock = 1; // we use the version 2 for dmd
        nMaxMoneyOut = 21000000 * COIN;

        const char* pszTimestamp = "30th April - Worx Birthday YAY!";
        CMutableTransaction txNew;
        txNew.vin.resize(1);
        txNew.vout.resize(1);
        txNew.vin[0].scriptSig = CScript() << 486604799 <<
CScriptNum(4) << vector<unsigned char>((const unsigned
char*)pszTimestamp, (const unsigned char*)pszTimestamp +
strlen(pszTimestamp));
        txNew.vout[0].nValue = 0 * COIN;
        txNew.vout[0].scriptPubKey = CScript() <<
ParseHex("0460f3c0dc9030b06deecde1dcdf38a0c964fca7b91f3af4891bf6d4afd19e0ca8c49c4be32514cf9cfe7d7815ea881784165b8cc04e56cadce0dd457d75215c08")
<< OP_CHECKSIG;
        genesis.vtx.push_back(txNew);
        genesis.hashPrevBlock = 0;
        genesis.hashMerkleRoot = genesis.BuildMerkleTree();
        genesis.nVersion = 1;
        genesis.nTime = 1527929962;
        genesis.nBits = 0x1e0ffff0;
        genesis.nNonce = 1203045;

        hashGenesisBlock = genesis.GetHash();

    //printf("%s\n", hashGenesisBlock.ToString().c_str());
    //printf("%s\n", genesis.hashMerkleRoot.ToString().c_str());

        assert(hashGenesisBlock ==
uint256("0x000003d2d9c72c327df1b3b2b94cfc07c9e788082ff23e14f06c53ac78d7c757"));
        assert(genesis.hashMerkleRoot ==
uint256("0x78c4cba5e2fdae012174f57f89628040e661d0bede071374e2f7cf10aaecc6b6"));


        vSeeds.push_back(CDNSSeedData("127.0.0.1", "127.0.0.1"));
        //vSeeds.push_back(CDNSSeedDataseed02.worx.global",
"seed02.worx.global"));
    //vSeeds.push_back(CDNSSeedData("seed03.worx.global",
"seed03.worx.global"));
        //vFixedSeeds.clear();
        //vSeeds.clear();

        base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1, 73);
        base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1, 135);
        base58Prefixes[SECRET_KEY] = std::vector<unsigned char>(1, 193);
        base58Prefixes[EXT_PUBLIC_KEY] =
boost::assign::list_of(0x04)(0x88)(0xB2)(0x1E).convert_to_container<std::vector<unsigned
char> >();
        base58Prefixes[EXT_SECRET_KEY] =
boost::assign::list_of(0x04)(0x88)(0xAD)(0xE4).convert_to_container<std::vector<unsigned
char> >();
        //     BIP44 coin type is from
https://github.com/satoshilabs/slips/blob/master/slip-0044.md 109
0x8000006d
        base58Prefixes[EXT_COIN_TYPE] =
boost::assign::list_of(0x80)(0x00)(0x00)(0x6d).convert_to_container<std::vector<unsigned
char> >();

        convertSeed6(vFixedSeeds, pnSeed6_main, ARRAYLEN(pnSeed6_main));

        fRequireRPCPassword = true;
        fMiningRequiresPeers = false;
        fAllowMinDifficultyBlocks = false;
        fDefaultConsistencyChecks = false;
        fRequireStandard = true;
        fMineBlocksOnDemand = false;
        fSkipProofOfWorkCheck = false;
        fTestnetToBeDeprecatedFieldRPC = false;
        fHeadersFirstSyncingActive = false;


        nPoolMaxTransactions = 3;
        strSporkKey =
"04104c1594c136ea1fc859321750518ef486c73eeb8db787b006d13211ad9d88162a2bb840ba03d3ee801fd85c7e47fb14f25110cf79b563106bcb178dac555bd1";
        strDarksendPoolDummyAddress = "AcmpqXViWUXNroqVNYRdKjKrFM6PNa1oTM";
        nStartMasternodePayments =1527929962;
    }

    const Checkpoints::CCheckpointData& Checkpoints() const
    {
        return data;
    }
};
static CMainParams mainParams;
```

**Comment by aboutboy** [comment]
somebody help me, tks：
lce@lce-VirtualBox:~/genesis-block$ python gen.py -a X11 -t 1517542208 -z "Don't work for weekends, work for our goals - 18/Jan/2018." -p "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f"
Traceback (most recent call last):
  File "gen.py", line 2, in <module>
    import mixhash
ImportError: No module named mixhash
