### ISSUE TITLE
Cannot get working it seems

### ISSUE THREAD

**Issue by ArenaCoinDev** [nasa8x/genesis-block#3]
root@mmocdev-VirtualBox:~/Desktop/TEST/genesis-block# python gen.py -a neoscript -t 1517542208 -z "Don't work for weekends, work for our goals - 18/Jan/2018." -p "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f"
Traceback (most recent call last):
  File "gen.py", line 6, in <module>
    from construct import *
ImportError: No module named construct

**Comment by ArenaCoinDev** [comment]
trying to generate a new blockchain for a neoscrypt test coin. cant seem to get this working for me. does anyone know the issue?

**Comment by nasa8x** [comment]
sudo pip install construct
or try node.js version
https://github.com/nasa8x/node-genesis-block

**Comment by ArenaCoinDev** [comment]
after installing construct this is my error

04ffff001d01043a446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c73202d2031382f4a616e2f323031382e
Traceback (most recent call last):
  File "gen.py", line 261, in <module>
    main()
  File "gen.py", line 18, in main
    tx = create_transaction(input_script, output_script,options)
  File "gen.py", line 76, in create_transaction
    Bytes("version", 4),
TypeError: __init__() takes exactly 2 arguments (3 given)
