### ISSUE TITLE
Keccak isn't working

### ISSUE THREAD

**Issue by thaistick** [nasa8x/genesis-block#5]
Hi

I can make all other algo to work to  generate genesis hash.
But can't make keccak256 to work.

Having this result :

```
$ python gen.py -a keccak -t 1517542208 -z "Don't work for weekends, work for our goals - 18/Jan/2018." -p "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f"
04ffff001d01043a446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c73202d2031382f4a616e2f323031382e
algorithm: keccak
merkle hash: 77fc7d6cfbc4ec91703444a515955092d4b7c04dbb8f23be59deb42a39ec0057
pszTimestamp: Don't work for weekends, work for our goals - 18/Jan/2018.
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
time: 1517542208
bits: 0x1e0ffff0
Searching for genesis hash...
Traceback (most recent call last):
  File "gen.py", line 261, in <module>
    main()
  File "gen.py", line 23, in main
    genesis_hash, nonce = generate_hash(block_header, algorithm, options.nonce, options.bits)
  File "gen.py", line 134, in generate_hash
    header_hash = generate_hashes_from_block(data_block, algorithm)
  File "gen.py", line 207, in generate_hashes_from_block
    return mixhash.Keccak(data_block)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/mixhash/__init__.py", line 21, in Keccak
    return keccak_hash.getPoWHash(x, len(x))
TypeError: function takes exactly 1 argument (2 given)
```

Can you help to fix that please, that would help a lot.

**Comment by auscash** [comment]
Yes, can we please have a fix for both genesis block creators.  Neither the node version or this works as expected.

**Comment by auscash** [comment]
clouduser@dev:~/genesis-block$ python gen.py -a keccak -t 1517542208 -z "Don't work for weekends, work for our goals - 18/Jan/2018." -p "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f"
04ffff001d01043a446f6e277420776f726b20666f72207765656b656e64732c20776f726b20666f72206f757220676f616c73202d2031382f4a616e2f323031382e
Traceback (most recent call last):
  File "gen.py", line 261, in <module>
    main()
  File "gen.py", line 18, in main
    tx = create_transaction(input_script, output_script,options)
  File "gen.py", line 76, in create_transaction
    Bytes("version", 4),
TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by thaistick** [comment]
hi

I will teach you how to do it on any code, without having to use generator,
for 0.05 BTC

Kind regards ;)

**Comment by thaistick** [comment]
I never succed with the generator.

I now do it with real way to build genesis hash.

using code and uncomment genesis part.

Build on Linux, start deamon, get error, then check log to see hash data.

Replace in code, rebuild wallet, you have a new blockchain.
